#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npm test

# pnpm exec lint-staged || (
#     echo '❌ PRE-COMMIT HOOK: Failed...'
#     echo '❌ Run format code with cmd: yarn beautiful'
#     false
# )
# echo '✅ PRE-COMMIT HOOK: Passed!'

yarn lint-staged
echo 'Run format code'

